### ISSUE TITLE
Bug : tag appears in analytics although not written

### ISSUE THREAD

**Issue by BenoitSerrano** [bamlab/commentor#159]
On my project, the tag "[prettier]" is repeated in the analytics every time I tag a comment on a Pull Request (cf. screenshot)

<img width="1437" alt="Capture d’écran 2020-06-22 à 17 13 14" src="https://user-images.githubusercontent.com/28384444/85304275-d984fc80-b4ab-11ea-8ada-5685ba5ee345.png">

**Comment by sraikimaxime** [comment]
@BenoitSerrano Hello ! Thank you for reporting this bug, it has been fixed. thanks to this commit: https://github.com/bamlab/commentor/commit/738cb69664bbbe1000f595f0341d996fb1f86865. Long story short, we were not escaping the tag codes so the square brackets were taken as a regexp element and matching all the comments showing a p, r, e, t or i
