### ISSUE TITLE
À propos de l'installation

### ISSUE THREAD

**Issue by thierrymarianne** [bamlab/commentor#8]
Salut ! 

Je me demande dans quelle mesure on peut compléter le README.md de manière à faciliter l'installation du projet sur un poste dédié au développement. :thinking:

**Comment by sraikimaxime** [comment]
@thierrymarianne Hello Thierry, ça t'as permit d'installer le projet ? :) si oui je ferme cette issue

**Comment by thierrymarianne** [comment]
Tout à fait ! Merci !

**Comment by sraikimaxime** [comment]
Hello Tierry, le fichier .env.example fait parti du fonctionnement de [dotenv-safe](https://github.com/rolodato/dotenv-safe) le fichier .example sert à la librairie à vérifier que tu as toutes les variables d'environnement dans  ton fichier .env qui est gitignoré :)

Pour ta deuxième question j'avoue que je ne comprends pas bien de quoi tu parles :) tu m'en dis plus ?

**Comment by thierrymarianne** [comment]
Compris pour les fchiers de configuration. Merci ! 

Pour 2., j'essaierai de fournir un exemple avec capture d'écran.

**Comment by sraikimaxime** [comment]
Vu ensemble je ferme cette issue :)
